-- ============================================================
--  FakeNewsDB  —  Oracle XE DDL
--  Run via SQL*Plus:
--    sqlplus fakenews/yourpassword@localhost/XEPDB1 @create_tables.sql
-- ============================================================

-- Drop tables if they already exist (safe re-run)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cross_dataset_performance CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE bias_scorecard CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE model_results CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE experiments CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE fnn_gc_dataset CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE fnn_pf_dataset CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE liar_dataset CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE isot_dataset CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE custom_news CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── 1. ISOT Dataset ──────────────────────────────────────────
CREATE TABLE isot_dataset (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR2(500),
    text          CLOB,
    subject       VARCHAR2(100),
    article_date  VARCHAR2(50),
    label         VARCHAR2(10)   -- 'FAKE' | 'REAL'
);

-- ── 2. LIAR Dataset ──────────────────────────────────────────
CREATE TABLE liar_dataset (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id   VARCHAR2(50),
    label          VARCHAR2(30),   -- false, half-true, mostly-true, etc.
    statement      CLOB,
    subjects       VARCHAR2(300),
    speaker        VARCHAR2(150),
    party          VARCHAR2(80),
    binary_label   VARCHAR2(10)    -- 'FAKE' | 'REAL' (derived)
);

-- ── 3. FakeNewsNet PolitiFact ─────────────────────────────────
CREATE TABLE fnn_pf_dataset (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id    VARCHAR2(100),
    news_url   VARCHAR2(1000),
    title      VARCHAR2(600),
    label      VARCHAR2(10)   -- 'FAKE' | 'REAL'
);

-- ── 4. FakeNewsNet GossipCop ──────────────────────────────────
CREATE TABLE fnn_gc_dataset (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id    VARCHAR2(100),
    news_url   VARCHAR2(1000),
    title      VARCHAR2(600),
    label      VARCHAR2(10)   -- 'FAKE' | 'REAL'
);

-- ── 5. Experiments ────────────────────────────────────────────
CREATE TABLE experiments (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_name  VARCHAR2(150),
    dataset_name     VARCHAR2(100),
    model_name       VARCHAR2(60),
    run_date         DATE DEFAULT SYSDATE,
    notes            VARCHAR2(1000)
);

-- ── 6. Model Results ──────────────────────────────────────────
CREATE TABLE model_results (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id    NUMBER,
    model_name       VARCHAR2(60),
    dataset_name     VARCHAR2(100),
    accuracy         NUMBER(7,4),
    f1_score         NUMBER(7,4),
    precision_score  NUMBER(7,4),
    recall_score     NUMBER(7,4),
    created_at       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_mr_exp FOREIGN KEY (experiment_id) REFERENCES experiments(id)
);

-- ── 7. Bias Scorecard ─────────────────────────────────────────
CREATE TABLE bias_scorecard (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name       VARCHAR2(60),
    dataset_name     VARCHAR2(100),
    label_bias       VARCHAR2(30),
    fake_accuracy    NUMBER(7,4),
    real_accuracy    NUMBER(7,4),
    disparity_score  NUMBER(7,4),
    evaluated_at     DATE DEFAULT SYSDATE
);

-- ── 8. Cross-Dataset Performance ─────────────────────────────
CREATE TABLE cross_dataset_performance (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name       VARCHAR2(60),
    train_dataset    VARCHAR2(100),
    test_dataset     VARCHAR2(100),
    accuracy         NUMBER(7,4),
    f1_score         NUMBER(7,4),
    evaluated_at     DATE DEFAULT SYSDATE
);

-- ── 9. Custom News Dataset ────────────────────────────────────
CREATE TABLE custom_news (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR2(500),
    text          CLOB,
    subject       VARCHAR2(100),
    label         VARCHAR2(10),
    created_at    DATE DEFAULT SYSDATE
);

-- ── Indexes for common queries ────────────────────────────────
CREATE INDEX idx_isot_label   ON isot_dataset(label);
CREATE INDEX idx_liar_label   ON liar_dataset(binary_label);
CREATE INDEX idx_fnnpf_label  ON fnn_pf_dataset(label);
CREATE INDEX idx_fnngc_label  ON fnn_gc_dataset(label);
CREATE INDEX idx_mr_model     ON model_results(model_name);
CREATE INDEX idx_cdp_model    ON cross_dataset_performance(model_name);

COMMIT;

PROMPT ✅  All 9 FakeNewsDB tables created successfully.
