import app
from app import get_connection

def setup_db():
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute("""
        CREATE TABLE custom_news (
            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title         VARCHAR2(500),
            text          CLOB,
            subject       VARCHAR2(100),
            label         VARCHAR2(10),
            created_at    DATE DEFAULT SYSDATE
        )
        """)
        conn.commit()
        print("Table 'custom_news' created successfully.")
    except Exception as e:
        print("Error or table already exists:", e)
    cur.close()
    conn.close()

if __name__ == "__main__":
    setup_db()
